name: SSX-Connector
main: xyz.derkades.ssx_connector.Main
version: '@project.version@'
author: Derkades
description: 'Addon plugin for ServerSelectorX'

commands:
  ssxc:
    aliases: [serverselectorxconnector, ssxconnector]
    usage: |
      /ssxc reload - Reload configuration files of all addons