# Ip adresses and port of hub servers
# Set the port in 'config.yml' in your ServerSelectorX folder
addresses:
- 'localhost:9782'

# Set the key in 'servers.yml' in your ServerSelectorX folder
key: 'put your key here'

# How often the connector plugin sends placeholders
# Use values 1-6 (3 means once every 3 seconds)
# You need to restart your server completely after changing this, /ssxc reload is not enough.
send-interval: 4