# Ip adresses and port of hub servers
# Set the port in 'config.yml' in your ServerSelectorX folder
addresses:
- 'localhost:9782'

# Set the key in 'servers.yml' in your ServerSelectorX folder
key: 'put your key here'